apiVersion: v1
kind: Service
metadata:
  name: llm-d-cpu-model-server
spec:
  selector:
    llm-d.ai/role: decode
    llm-d.ai/guide: minikube-llm-d-cpu
  ports:
    - name: modelserver
      port: 8000
      targetPort: modelserver
      protocol: TCP
  type: ClusterIP
