apiVersion: v1
kind: Service
metadata:
  name: llmd-auth-service
  labels:
    app: secure-inference
spec:
  ports:
    - port: 4444
      targetPort: {{ .Values.authPort }}
      protocol: TCP
      name: grpc-auth
      appProtocol: kubernetes.io/h2c
  selector:
    app: secure-inference
